### ISSUE TITLE
Async command handler not registering

### ISSUE THREAD

**Issue by aradoje** [Happyr/SimpleBusBundle#5]
When command is async handler is not registered with `asynchronous_command_handler` tag name. It throws an error:
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "command_handler.some_command_handler.auto". Did you mean this: "app.command_handler.somecommandhandler"?
```
 If remove async everything is ok. 

`.yml` for handler:
```
services:
  app.command_handler.SomeCommandHandler:
      class: App\Message\CommandHandler\SomeCommandHandler
      arguments: ["@app.some_service"]
      tags:
        - { name: asynchronous_command_handler, handles: App\Message\Command\SomeCommand}
```
